api/src/db/helpers/book_endpoint.rs, api/src/db/tests/db_tests.rs, api/src/query_models/book.rs, api/tests/book_endpoint_tests.rs
- This adds feature to retrieve books by `designation_id`. 
- This also adds tests to cover the request with multiple queries. 
- Test logic has been changed from `filter` to `all` to cover multiple queries and to fix the bug when test function could retrieve incorrect results before filtering.
=> Feature get books with designationid with tests

api/src/db/helpers/book_endpoint.rs, api/src/db/tests/db_tests.rs, api/src/query_models/book.rs, api/tests/book_endpoint_tests.rs
- This adds feature to retrieve books by `designation_id`. 
- This also adds tests to cover the request with multiple queries. 
- Test logic has been changed from `filter` to `all` to cover multiple queries and to fix the bug when test function could retrieve incorrect results before filtering.
=> Feature get books with designation id with tests

identity/src/config.rs
This port is also specified as default in `api::config` as `IDENTITY_SERVICE_HOST_PORT`.
=> identity: change default RPC_HOST_PORT to 8081

.github/workflows/cd-dev-api.yml, .github/workflows/cd-dev-book.yml, .github/workflows/cd-dev-borrow.yml, .github/workflows/cd-dev-identity.yml, .github/workflows/cd-dev-notification.yml
This adds `Cargo.lock` to the paths of all continuous delivery workflows. The fact that we do not have patch versions any more in the `Cargo.toml` files leads to the fact that Dependabot updates only update the `Cargo.lock` file. This will not run the respective workflows for pushing an updated version of the applications.
=> Add Cargo.lock to continuous delivery pipeline

Cargo.lock, api/Cargo.toml, book/Cargo.toml, borrow/Cargo.toml, identity/Cargo.toml, notification/Cargo.toml
Tokio causes a panic, because some of our other dependencies still have version `0.2`, which is incompatible with `0.3`.
This reverts commit 4cc4235544b433a180f3e7b77d5cf1f713e45ed3.
=> Revert "Bump tokio from 0.2.22 to 0.3.0"

book/src/config.rs, borrow/src/config.rs, notification/src/config.rs
After this change the ports will be as follows:
* `api` 8080
* `identity` 8081
* `book` 8082
* `borrow` 8083
* `notification` 8084
=> Make default microservice server ports unique

identity/src/main.rs
This PR raises the channel limit per ip for the identity microservice to `11`. The value equates to the number of endpoints in the respective rpc service.
=> Changes the channel limit per ip for the identity microservice

book/Cargo.toml, book/src/lib.rs, book/src/main.rs
Enables more flexible importing of components into other crates,
which is also useful for testing.
=> Split book into binary and library target

api/src/endpoints/identity.rs, api/src/lib.rs, api/src/middleware.rs, api/src/response.rs
* add `mod error`: contains helper functions for warp error replies
* Adapt `enpoints::identity`, `middleware` to error module
=> api: Unify error handling

identity/migrations/2020-11-02-210000_add_unique_roles/down.sql, identity/migrations/2020-11-02-210000_add_unique_roles/up.sql
The migration for the identity microservice had the roles missing, which are required to successfully run the service. This adds the roles and also makes the role names unique to prevent a future name clash.
=> Add unique roles migration for identity microservice

Cargo.lock, book/src/db/models.rs, helpers/Cargo.toml, helpers/src/lib.rs, helpers/src/rpc.rs, identity/src/rpc/service.rs
Error type to be used in-between api and rpc-services
=> Helpers: Add `enum Error`

book/src/db/models.rs, book/src/lib.rs, book/src/rpc/mod.rs, book/src/rpc/models.rs, book/src/rpc/server.rs, book/src/rpc/service.rs
* mv `db::models::*` to `rpc::models::*`
* mv `fn rpc_server(...)` to `mod rpc`
* replace `pub mod ...` with `pub use crate::rpc::*`
=> book: Restructure lib

book/src/rpc/models.rs, book/src/rpc/server.rs, book/src/rpc/service.rs, helpers/src/rpc.rs, identity/src/rpc/server.rs, identity/src/rpc/service.rs
This PR adds the type `RpcResult`, to the `helpers` crate. Usage of this type makes rpc method return types a bit simpler, as we always return `Result<T, Error>`, while Error is `helpers::rpc::Error`.
=> Adds result type for rpc and refactors code accordingly

book/src/db/queries.rs, book/src/rpc/models.rs
While doing #136 I overlooked that a book might not have a series and the field in the return-type should thereby be optional. This PR fixes this.
=> `book`: make series optional

.github/workflows/ci.yml
This service will be started along the CI-runner for tests,
so we can test against an actual postgres database.
=> CI: Set up postgres service container for tests

.github/workflows/ci.yml
This avoids that the wrong workflow runs in a PR
=> CI: Run on pull_request

book/src/db/queries.rs, book/src/rpc/server.rs, helpers/src/rpc.rs
This PR implements an adapter from `diesel::result::Error` to our custom error type. This is useful because we now don't need to match it manually in 98% of the cases, but only when we don't want the default behaviour.
The PR includes a 2nd commit showcasing this. Additionally it can be used in `identity/src/rpc/server.rs`.
=> `helpers::rpc`: `impl From<diesel::result::Error> for Error`

helpers/src/db/mod.rs, helpers/src/db/pagination.rs, helpers/src/rpc.rs
This adds a database pagination module to the helpers crate. The pagination feature can split the results in pages and return the number of pages.
```
<table>
.filter(<some-filter>)
.paginate(<page>)
.per_page(<results-per-page>)
.load_and_count_pages(<db-connection>)
```
Returns a `<Vec<T>, i64>`, where T is the model type.
=> Adds database pagination module to helpers crate

.github/workflows/cd-dev-api.yml, .github/workflows/cd-dev-book.yml, .github/workflows/cd-dev-borrow.yml, .github/workflows/cd-dev-identity.yml, .github/workflows/cd-dev-notification.yml
This PR unifies the currently two jobs of the cd-workflows into one.
Additional simplifications:
* drop up- and downloading of docker image
_(we can keep the upload if you want, but I'd vote for not to)_
* move `env` specification from individual `step`s to whole `job`
* rm additional tagging step (not needed anymore)
=> CD: Unify jobs

identity/src/lib/config.rs, identity/src/lib/db/mod.rs, identity/src/lib/rpc/server.rs, identity/src/main.rs
Removes global static configuration and database from identity service. The motivation for this change is to provide better support for testing.
=> Removes global static configuration and database from identity service

book/src/lib/db/models.rs
This error resulted in `diesel` deserializing the `name` into `iso_code` and vice-versa.
=> `book::db::models`: Fix attribute order of `Language`

identity/src/lib/rpc/mod.rs, identity/src/lib/rpc/models.rs, identity/src/lib/rpc/server.rs, identity/src/lib/rpc/service.rs, identity/tests/rpc_endpoints.rs
This PR moves the rpc models from `service.rs` into `models.rs` to better separate them.
=> Move identity service rpc models into their own module

book/src/lib/db/models.rs, book/src/lib/rpc/models.rs, book/src/lib/rpc/server.rs
This PR uses serde field attributes ([see here](https://serde.rs/field-attrs.html)) to remove state duplication in the book service.
=> `book`: Simplify models through serde magic

identity/tests/rpc_endpoints.rs
This PR makes the rpc tests respects environment variables set in the environment, instead of providing always the defaults for testing.
=> Makes tests respect preset environment variables

identity/src/lib/authentication/mod.rs, identity/src/lib/authentication/oauth.rs, identity/src/lib/db/queries.rs, identity/src/lib/rpc/models.rs, identity/src/lib/rpc/server.rs, identity/src/lib/rpc/service.rs, identity/tests/db_queries.rs, identity/tests/rpc_endpoints.rs
* Adds integration test for OAuth authentication rpc endpoint
* Various simplifications for rpc OAuth authentication endpoint
* Unifies error return from OAuth authentication to provide conversion to RpcError
* Adds `check_account_status` function
* Adds `create_user_from_oauth_authentication` function
* Adds db query to update user by `sub` attribute
* Adds comments to OAuth authentication rpc endpoint
=> Identity oauth refactoring

Cargo.lock, book/Cargo.toml
This PR downgrades the `uuid` module, currently used in the `book` service. If diesel is used with support for UUIDs, two different versions can create conflicts and extends the compilation time a bit. We will stick to this version until the next version of Diesel supports the latest UUID module version.
=> Downgrades the uuid module version to 0.7

Cargo.lock, identity/Cargo.toml, identity/migrations/2020-12-14-110000_migrate_uuid/down.sql, identity/migrations/2020-12-14-110000_migrate_uuid/up.sql, identity/src/lib/authentication/mod.rs, identity/src/lib/db/models.rs, identity/src/lib/db/queries.rs, identity/src/lib/db/schema.rs, identity/src/lib/rpc/models.rs, identity/src/lib/rpc/server.rs, identity/src/lib/rpc/service.rs, identity/src/lib/session/jwt.rs, identity/tests/db_queries.rs, identity/tests/rpc_endpoints.rs, identity/tests/sample_data.rs
Adds a migration for the identity service to remove the integer ids and replace them with UUIDs. Also, changes the models and tests accordingly. This PR is part of a bigger refactoring, to also improve the database testing.
=> Identity service - Migrate user identifiers to UUID

book/migrations/20210208110427_initial_schema.down.sql, book/migrations/20210208110427_initial_schema.up.sql, book/src/lib/db/models.rs, book/src/lib/rpc/models.rs
* Renames field `code_identifier_copy_id` to `copy_id` on table `copies` in database migrations.
* Renames field `code_identifier_copy_id` to `copy_id` on table `copies` in database models.
* Adds database function and trigger `copies_copy_id_create_seq` to database migrations.
* Adds database function and trigger `copies_copy_id_delete_seq` to database migrations.
=> Adds automatic generation for book copy ids
