Cargo.lock, Cargo.toml, src/api/endpoints/book.rs, src/api/endpoints/borrow.rs, src/api/endpoints/identity.rs, src/api/endpoints/mod.rs, src/api/endpoints/notification.rs, src/api/endpoints/root.rs, src/api/main.rs, src/api/router.rs
Adds warp crate as a dependency. Introduces a routing and endpoint module.
=> Warp migration

.gitignore
This will add the ".env" file to the ".gitignore" file.
=> Added '.env' files to gitignore

.env
Remove .env file from repository index.
=> Remove .env file from repository

README.md
Latest version of readme file.
=> Documentation readme file

ARCHITECTURE.md, README.md, api/README.md, api/REST-API.md, book/README.md, borrow/README.md, identity/README.md, notification/README.md
* Update README.md
* Add backend architecture documentation in ARCHITECTURE.md
* Add README.md for services IDENTITY, BOOK, BORROW and NOTIFICATION
* Add REST API documentation for service API
=> Update backend documentation

README.md, book/README.md, borrow/README.md, identity/README.md, notification/README.md
Fixes formatting and adds warnings in the README files.
=> Documentation readme

Cargo.lock, book/Cargo.toml, book/src/main.rs, borrow/Cargo.toml, borrow/src/main.rs, identity/Cargo.toml, identity/src/main.rs, notification/Cargo.toml, notification/src/main.rs
This implements basic logging and service start information.
=> Add logging dependencies and service start logging

Cargo.lock, book/Cargo.toml, book/src/config.rs, book/src/main.rs, borrow/Cargo.toml, borrow/src/config.rs, borrow/src/main.rs, identity/Cargo.toml, identity/src/config.rs, identity/src/main.rs, notification/Cargo.toml, notification/src/config.rs, notification/src/main.rs
Add configuration dependencies and static configuration data structure
* Add lazy_static dependency
* Add dotenv dependency
* Add envconfig dependency
* Add configuration data structure
* Add configuration initialization in lazy_static
=> Add configuration dependencies and static configuration data structure

Cargo.lock, book/Cargo.toml, book/src/main.rs, borrow/Cargo.toml, borrow/src/main.rs, identity/Cargo.toml, identity/src/main.rs, notification/Cargo.toml, notification/src/main.rs
This change provides the foundation to run the services async.
=> Update main function to async

Cargo.lock, book/Cargo.toml, book/src/config.rs, book/src/main.rs, borrow/Cargo.toml, borrow/src/config.rs, borrow/src/main.rs, identity/Cargo.toml, identity/src/config.rs, identity/src/main.rs, notification/Cargo.toml, notification/src/config.rs, notification/src/main.rs
This adds the environment variable configuration for the database and the database initialization through a lazy_static.
=> Feature database connection

.circleci/config.yml, api/slim.Dockerfile
This adds `circleci` config for deployment to GCR and GKE
=> GKE set up

api/REST-API.md
This PR does some minor cleanups:
* `cargo fmt`
* Clean `api/REST-API.md`
* autoformat tables (with VS Code)
* make routes collapsable
=> Doc cleanup

Cargo.lock, api/Cargo.toml, api/src/rpc/client_connections.rs, book/Cargo.toml, borrow/Cargo.toml, identity/Cargo.toml, notification/Cargo.toml
* resolve breaking change (https://github.com/google/tarpc/blob/master/RELEASES.md#breaking-changes)
=> Bump tarpc from 0.21 to 0.22

book/src/db/queries.rs
* rm intermediate variables
* make util functions private
=> `book::db::queries`: simplify `fn get_book_by_id`

book/migrations/2020-11-11-132222_alter_lang/down.sql, book/migrations/2020-11-11-132222_alter_lang/up.sql, book/migrations/2020-11-11-133612_fill_base_data/down.sql, book/migrations/2020-11-11-133612_fill_base_data/up.sql, book/src/db/models.rs
* `book::migrations`: ALTER TABLE languages
* `book::migrations`: Fill base data (categories, languages)
=> book db base setup

api/src/endpoints/book.rs, api/src/router.rs, book/src/db/queries.rs, book/src/rpc/models.rs, book/src/rpc/server.rs, book/src/rpc/service.rs
* `api::{router, middleware::book}`: Extract query parameters and resolve into HTTP response.
* `book::{rpc, db::queries}`: Query page of books + additional attributes. Assemble them on application level.
=> Implement `GET /book/?page={u32}[&page_size={u32}]`

book/src/db/queries.rs
SQL created using `diesel::debug_query(&query)`
=> `book::db::queries`: Document queries with SQL

identity/src/lib/config.rs, identity/src/lib/db/mod.rs, identity/src/lib/db/models.rs, identity/src/lib/rpc/server.rs, identity/src/lib/session/jwt.rs, identity/src/main.rs
Applies the the import scheme, proposed in #154 PR, to the identity service.
=> Updates imports in identity service according to new import schema

api/src/endpoints/book.rs
=> `api::endpoints::book`: Make query param `page` optional

api/openapi.yml
* `openapi.yml`: Clean up (page width: 88)
```
Page width choosen because of https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length
```
* `api/openapi.yml`: add `GET /book[?page={u32}&page_size={u32}]`
=> openapi: add book list

identity/src/lib/rpc/models.rs, identity/src/lib/rpc/server.rs, identity/src/lib/session/jwt.rs, identity/tests/rpc_endpoints.rs
* Switch from SystemTime to chrono module
* Make the constructor of JWT struct a pure function
* Add from trait implementation for JWT to SessionToken
=> Identity session jwt module refactoring

Cargo.lock, book/Cargo.toml, book/src/lib/db/models.rs, book/src/lib/db/queries.rs, book/src/lib/lib.rs, book/src/lib/rpc/models.rs, book/src/lib/test_data.rs, book/tests/integration.rs
* `book`: Add `mod test_data` (hidden behind feature "test-data")
* `book::tests::end_to_end`: Setup end-to-end testing
* 2 tests:
* `should_not_find_book`
* `should_find_book`
* `utils`
* Start rpc server and connect client
* Create dummy database + run migrations
* fill test data
=> test: book-db-integration

api/src/lib/endpoints/book.rs, api/src/lib/router/book.rs, book/src/lib/db/queries.rs, book/src/lib/rpc/server.rs, book/src/lib/rpc/service.rs, helpers/src/filters/book.rs, helpers/src/filters/mod.rs
* Adds a book filter data structure, to filter for categories, publishers, subject_areas, and tags.
* Implements the filter to the book list endpoint in the BOOK service.
* Implements the filter to the book list endpoint in the API service.
=> Adds book filter

.github/workflows/ci.yml
Moves the `continue-on-error` from the job to the steps level.
=> Moves continue-on-error declaration
